language: php

php:
  - 5.3
  - 5.4

env:
 - DB=mysql
 - DB=pgsql
 - DB=sqlite

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --prefer-dist
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database redkite_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database redkite_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then php app/console redkitecms:configure --driver=sqlite --host=localhost --database=redkite --no-interaction; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then php app/console redkitecms:configure --driver=mysql --host=localhost --port=3306 --database=redkite --user=travis --password= --no-interaction; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then php app/console redkitecms:configure --driver=pgsql --host=localhost --port=5432 --database=redkite --user=postgres --password= --no-interaction; fi"
  - sh -c "php app/console propel:sql:insert --force --env=rkcms_test"
  - php app/console redkitecms:install --env=rmcms

script: phpunit -c app

notifications:
  email:
    - info@alphalemon.com
