language: php

php:
  - 5.3
  - 5.4

# env:
#  - DB=mysql
#  - DB=pgsql
#  - DB=sqlite

before_script:
  #- mysql -e 'create database redkite_test;'
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev
  - php app/console redkitecms:install --driver=sqlite --host=localhost --database=redkite_test --no-interaction

script: phpunit -c app

notifications:
  email:
    - info@alphalemon.com
